### ISSUE TITLE
Interpreter does not compile due to no 'rand' crate.

### ISSUE THREAD

**Issue by Notsoartificialintelligence** [RocketRace/babalang#1]
If I attempt to compile using the provided rustc command, I get the following error:

```
error[E0432]: unresolved import `rand`
  --> src\interpreter.rs:16:5
   |
16 | use rand::random;
   |     ^^^^ maybe a missing crate `rand`?
   |
   = help: consider adding `extern crate rand` to use the `rand` crate
```

I have tried changing both the interpreter.rs and main.rs files in order to fix this error, along with updating the dependencies in the Cargo.toml file. This error only occurs when compiling using rustc, but if I try to compile using cargo I am still unable to use the ```babalang``` command as the interpreter has not correctly compiled.

**Comment by Notsoartificialintelligence** [comment]
I should also specify that I have tried to add "extern crate rand;" into main.rs before this, but removed it after no success.

**Comment by pulustelu** [comment]
Thanks, there seems to be an oversight in the readme, since the command only works as-is without dependencies. The recommended way to build the project is using `cargo`. I'll remove it since this is kind of what cargo is designed for.

**Comment by Notsoartificialintelligence** [comment]
thanks!
